cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'ack'
brew 'git'
brew 'heroku-toolbelt'
brew 'hub'
brew 'htop'
brew 'ctags'
brew 'zsh'
brew 'zsh-syntax-highlighting'
brew 'vim'
brew 'tmux'
brew 'tree'
brew 'readline'
brew 'the_silver_searcher'
brew 'ruby-build'
brew 'rbenv'
brew 'python3'
brew 'imagemagick'
brew 'node'
brew 'libyaml'
brew 'postgres', restart_service: true
brew 'redis', restart_service: true
brew 'reattach-to-user-namespace'
brew 'qt'
brew 'grc'
brew 'httpie'

cask '1password'
cask 'google-chrome'
cask 'firefox'
cask 'steam'
cask 'vlc'
cask 'transmission'
cask 'spotify'
cask 'dropbox'
cask 'alfred'
cask 'iterm2'
cask 'evernote'
cask 'flux'
cask 'skype'
cask 'spectacle'
